### ISSUE TITLE
Feature: configurable API endpoint

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [mollie/oauth2-mollie-php#12]
During https://status.mollie.com/incidents/0x73qvqpkkb1 our server is somehow unable to resolve mollie.nl (due to some network changes maybe?). The `Mollie_API_Client` has a method `setApiEndpoint()` to manually configure .com instead of .nl, but in the OAuth client the endpoint is hardcoded.

As a quick workaround / hack I manually changed the endpoint URL, but it would be nice to be able to pass it in the Client constructor or have a method for it.

**Comment by sandervanhooft** [comment]
Hi @SanderVanLeeuwen,

Good thinking, but I guess there's not much demand for this. I'm closing this for now, feel free to submit a PR (and I'll reopen this issue).
