### ISSUE TITLE
Use AccessTokenInterface as of league/oauth2-client 2.4.0

### ISSUE THREAD

**Issue by holtkamp** [mollie/oauth2-mollie-php#14]
[league/oauth2-client `2.4.0`](https://github.com/thephpleague/oauth2-client/releases/tag/2.4.0) introduced a `AccessTokenInterface`. 

Not using it causes an error:

```
PHP Fatal error:  Declaration of Mollie\OAuth2\Client\Provider\Mollie::getResourceOwnerDetailsUrl(League\OAuth2\Client\Token\AccessToken $token) must be compatible with League\OAuth2\Client\Provider\AbstractProvider::getResourceOwnerDetailsUrl(League\OAuth2\Client\Token\AccessTokenInterface $token) in /project/vendor/mollie/oauth2-mollie-php/src/Provider/Mollie.php on line 10
```

Forced use of league/oauth2-client `2.3.1` resolves this problem, I think this should be set as the "maximum" version of `league/oauth2-client` that can be used with "this" version of `mollie/oauth2-mollie-php`

**Comment by holtkamp** [comment]
**UPDATE**
This was clearly a non-backward compatible change, also discussed here: https://github.com/thephpleague/oauth2-client/issues/752

**Comment by willemstuursma** [comment]
Thanks for reporting anyway.

**Comment by ramsey** [comment]
Please check release 2.4.1 of `league/oauth2-client` and confirm that it fixes this issue. Thanks!

**Comment by holtkamp** [comment]
@ramsey thanks for the swift patch release, this indeed resolves the issue.
