### ISSUE TITLE
Package phpunit/phpunit-mock-objects is abandoned

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/oauth2-mollie-php#16]
Tests are running fine though.

**Comment by willemstuursma** [comment]
Can probably be fixed by upgrading PHPUnit.

**Comment by sandervanhooft** [comment]
Which version do you prefer?

**Comment by sandervanhooft** [comment]
Upgrading to phpunit > 5 requires us to drop php 5.6 support.

We're not ready to do that and all works fine, so closing this issue.
