### ISSUE TITLE
Additional getters for MollieResourceOwner to retrieve information useful during registration of an OAuth2 App

### ISSUE THREAD

**Issue by holtkamp** [mollie/oauth2-mollie-php#22]
It seems [MollieResourceOwner only has "getId()"](https://github.com/mollie/oauth2-mollie-php/blob/fde192ded4e79f5016fe001131ca14805cb135a2/src/Provider/MollieResourceOwner.php#L29-L32) to retrieve the Mollie ID.

Would it be an idea to also add getters for [documented information that might be useful to lookup an organization](https://docs.mollie.com/reference/v2/organizations-api/get-organization) like `email`, `registrationNumber`, `vatNumber`, etc. 

For example:

```php
public function getEmail(): ?string
{
    return $this->response['email'] ?? null;
}

public function getRegistrationNumber(): ?string
{
    return $this->response['registrationNumber'] ?? null;
}

public function getVatNumber(): ?string
{
    return $this->response['vatNumber'] ?? null;
}
````

**Comment by sandervanhooft** [comment]
I like it @holtkamp ! Can you whip up a PR?

**Comment by holtkamp** [comment]
I can give it a try, is PHP 5.6 still the minimal target version to support? 😨 

https://github.com/mollie/oauth2-mollie-php/blob/fde192ded4e79f5016fe001131ca14805cb135a2/composer.json#L19

**Comment by sandervanhooft** [comment]
Hi @holtkamp,

Much appreciated!

Php5.6: I'm afraid so.
