### ISSUE TITLE
Missing scope for payment-links.read/write

### ISSUE THREAD

**Issue by erikkraijenoord** [mollie/oauth2-mollie-php#28]
Hi,

We are working on a solution to automaticly send a payment URL, for this we have integrated Mollie because all other actions are done this way as well. But we are unable to find the correct scope for payment-links.read/write, do we use a different scope or is this option missing in the code?

https://github.com/mollie/oauth2-mollie-php/blob/3dcb2ff28e246a9aef4f322116e521939de1be14/src/Provider/Mollie.php#L53-L82

**Comment by sandervanhooft** [comment]
Fixed in #29

**Comment by sandervanhooft** [comment]
Patch released here: https://github.com/mollie/oauth2-mollie-php/releases/tag/v2.6.0
