### ISSUE TITLE
Missing information about how to integrate with mollie-api-php

### ISSUE THREAD

**Issue by timmipetit** [mollie/oauth2-mollie-php#30]
Information about how to use an access token generation by this library in combination with the mollie PHP API client seems to be missing. I would suggest updating the documentation with something like this:

```php
$mollie = new \Mollie\Api\MollieApiClient();
$mollie->setAccessToken($token);
```

**Comment by sandervanhooft** [comment]
All done! Thanks for reporting.

https://github.com/mollie/oauth2-mollie-php/blob/master/README.md#authenticating-using-the-accesstoken-mollie-api-php-example
