### ISSUE TITLE
MOLLIE_WEB_URL for Oauth authorization should be updated

### ISSUE THREAD

**Issue by StefanNiederkofler** [mollie/oauth2-mollie-php#33]
As described in the documentation, the URL for the OAuth auth should be "https://my.mollie.com/".
https://docs.mollie.com/reference/authorize

Currently it is set as follows:
`const MOLLIE_WEB_URL = 'https://www.mollie.com';`

Which is used in
```
public function getBaseAuthorizationUrl(): string
{
    return $this->mollieWebUrl . '/oauth2/authorize';
}
```

**Comment by sandervanhooft** [comment]
Hi @StefanNiederkofler ,

Thanks for opening this ticket. Let me look into it.

**Comment by sandervanhooft** [comment]
You're right! The oauth2 authentication page url was silently updated to my.mollie.com. Updating it [here](https://github.com/mollie/oauth2-mollie-php/pull/34).

**Comment by sandervanhooft** [comment]
And released!

https://github.com/mollie/oauth2-mollie-php/releases/tag/v2.8.1

Thanks again @StefanNiederkofler !
