### ISSUE TITLE
App is in demo mode warning

### ISSUE THREAD

**Issue by AntonShumin** [mollie/oauth2-mollie-php#6]
I am trying make an Authorize call and keep getting the "this app is in demo mode" error when granting premissions. 

![image](https://cloud.githubusercontent.com/assets/5438507/26151638/fcae9ea2-3b03-11e7-9a31-e6aa9314c57b.png)

I dont recall any testmode setting for the app. 
I am however calling the script from localhost. Could that be an issue?

**Comment by willemstuursma** [comment]
Initially, the app is only available for installing in your own account. 

If you want to open up the app to all of our merchants, please reach out to our support desk so we can validate your app and account.
