### ISSUE TITLE
RandomLib usage in project - deprecated warnings PHP7.1+

### ISSUE THREAD

**Issue by thinkalikenl** [mollie/oauth2-mollie-php#9]
I am using the Mollie Connect API and currently stuck on PHP 7.0, because the API makes use of RandomLib. This in turn uses mcrypt, which generates E_DEPRECATED warnings in PHP7.1 and is completely removed in PHP7.2. Can randomlib be exchanged with a library compatible with PHP7.1+?

[mollie_connect_php71.pdf](https://github.com/mollie/oauth2-mollie-php/files/1531372/mollie_connect_php71.pdf)

**Comment by willemstuursma** [comment]
The calls are in `RandomLib`, a dependency of `league/oauth2-client`.

You should switch to `league/oauth2-client:^2.0`, which stopped using `RandomLib`.
